# Generated by Django 2.1.4 on 2018-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='picture',
            field=models.ImageField(upload_to='art_images'),
        ),
    ]
