# Generated by Django 2.1.4 on 2018-12-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181206_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='picture',
            new_name='real_img',
        ),
        migrations.RemoveField(
            model_name='art',
            name='original_title',
        ),
    ]
